<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Electro\models\Bill;

use Atlas\Table\Row;

/**
 * @property mixed $ID int(10,0) NOT NULL
 * @property mixed $PaymentAmount decimal(5,2) NOT NULL
 * @property mixed $PaymentDate date NOT NULL
 * @property mixed $User int(10,0) NOT NULL
 */
class BillRow extends Row
{
    protected $cols = [
        'ID' => null,
        'PaymentAmount' => '0.00',
        'PaymentDate' => null,
        'User' => null,
    ];
}
