/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java
	eclipse
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

sourceSets {
	main {
		java {
			setSrcDirs(listOf("spark/src"))
		}
		resources {
			setSrcDirs(listOf("spark/resources"))
		}
	}
	test {
		java {
			setSrcDirs(listOf("spark/test"))
		}
	}
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.google.guava:guava:27.0.1-jre")
	implementation("com.sparkjava:spark-core:2.9.0")
	implementation("org.slf4j:slf4j-simple:1.7.25")
	implementation("com.google.code.gson:gson:2.8.5")
	implementation("org.jooq:jooq:3.11.11")
	implementation("io.github.cdimascio:java-dotenv:5.0.1")
	implementation("mysql:mysql-connector-java:8.0.11")
	implementation("com.zaxxer:HikariCP:3.3.1")
	implementation("org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final")

    // Use JUnit test framework
	testImplementation("org.junit.jupiter:junit-jupiter:5.4.2")
}