CREATE DATABASE IF NOT EXISTS Electro;

CREATE TABLE IF NOT EXISTS Users (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Username VARCHAR(30) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS Bills (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	User INT NOT NULL,
	PaymentAmount DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
	PaymentDate DATE NOT NULL,
	FOREIGN KEY (User) REFERENCES Users(ID)
);