<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Electro\models\User;

use Atlas\Table\Table;

/**
 * @method UserRow|null fetchRow($primaryVal)
 * @method UserRow[] fetchRows(array $primaryVals)
 * @method UserTableSelect select(array $whereEquals = [])
 * @method UserRow newRow(array $cols = [])
 * @method UserRow newSelectedRow(array $cols)
 */
class UserTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'Users';

    const COLUMNS = [
        'ID' => [
            'name' => 'ID',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'Username' => [
            'name' => 'Username',
            'type' => 'varchar',
            'size' => 30,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'Password' => [
            'name' => 'Password',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'ID',
        'Username',
        'Password',
    ];

    const COLUMN_DEFAULTS = [
        'ID' => null,
        'Username' => null,
        'Password' => null,
    ];

    const PRIMARY_KEY = [
        'ID',
    ];

    const AUTOINC_COLUMN = 'ID';

    const AUTOINC_SEQUENCE = null;
}
